[project]
name = "markdown2pdf-base"
version = "0.2.3"
description = "Convert Markdown to PDF using markdown2html5-base and pandoc"
readme = "README.md"
requires-python = ">=3.10"
authors = [
    { name = "Anatoly Shcherbina", email = "avshcherbina@gmail.com" }
]
dependencies = [
    "markdown2html5-base >= 0.2.4"
]
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

[project.optional-dependencies]
test = [
    "pytest"
]

[project.scripts]
markdown2pdf-base = "markdown2pdf_base.cli:main"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.isort]
profile = "black"
